# Generated by Django 4.1.1 on 2022-10-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_alter_movie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_added',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
