# Generated by Django 4.1.1 on 2022-10-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_alter_movie_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date_added',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
