# Generated by Django 4.1.1 on 2022-10-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0012_alter_movie_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_launch',
            field=models.DateField(blank=True, null=True),
        ),
    ]
