# Generated by Django 4.1.1 on 2022-10-22 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0013_movie_date_launch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='date_launch',
        ),
    ]
